"""empty message

Revision ID: b2916f6f0dfe
Revises: 
Create Date: 2022-07-05 16:46:40.032197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2916f6f0dfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rocket_id', sa.VARCHAR(length=80), nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=80), nullable=True),
    sa.Column('personal_email', sa.VARCHAR(length=80), nullable=True),
    sa.Column('work_email', sa.VARCHAR(length=80), nullable=True),
    sa.Column('work_ntlm', sa.VARCHAR(length=80), nullable=True),
    sa.Column('work_ntlmv2', sa.VARCHAR(length=80), nullable=True),
    sa.Column('work_password', sa.VARCHAR(length=80), nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=80), nullable=True),
    sa.Column('ctime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
